version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx/conf.d/default.conf
    depends_on:
      - node

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: node server.js
